//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anamnesis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anamnesis()
        {
            this.Antecedentes = new HashSet<Antecedentes>();
        }
    
        public int IdAnamnesis { get; set; }
        public string Diabetes { get; set; }
        public string Epilepsia { get; set; }
        public string TBC { get; set; }
        public string EnfRespiratorias { get; set; }
        public string CardiopatiasH { get; set; }
        public string Alergias { get; set; }
        public string HepatitisVIH { get; set; }
        public string EnfGastro { get; set; }
        public string Hemorragias { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Habilitado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antecedentes> Antecedentes { get; set; }
    }
}
