//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ConsultorioOdonBDEntities1 : DbContext
    {
        public ConsultorioOdonBDEntities1()
            : base("name=ConsultorioOdonBDEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anamnesis> Anamnesis { get; set; }
        public virtual DbSet<Antecedentes> Antecedentes { get; set; }
        public virtual DbSet<Condiciones> Condiciones { get; set; }
        public virtual DbSet<Consultas> Consultas { get; set; }
        public virtual DbSet<Departamentos> Departamentos { get; set; }
        public virtual DbSet<DetallesFacturas> DetallesFacturas { get; set; }
        public virtual DbSet<Empleados> Empleados { get; set; }
        public virtual DbSet<Examenes> Examenes { get; set; }
        public virtual DbSet<ExamenesClinicos> ExamenesClinicos { get; set; }
        public virtual DbSet<ExamenesComplementarios> ExamenesComplementarios { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<HistoriasClinicas> HistoriasClinicas { get; set; }
        public virtual DbSet<Municipios> Municipios { get; set; }
        public virtual DbSet<Odontogramas> Odontogramas { get; set; }
        public virtual DbSet<Pacientes> Pacientes { get; set; }
        public virtual DbSet<PacientesResponsables> PacientesResponsables { get; set; }
        public virtual DbSet<Paginas> Paginas { get; set; }
        public virtual DbSet<Radiografias> Radiografias { get; set; }
        public virtual DbSet<Responsables> Responsables { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<RolesPaginas> RolesPaginas { get; set; }
        public virtual DbSet<Sexos> Sexos { get; set; }
        public virtual DbSet<Sueldos> Sueldos { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TiposContratos> TiposContratos { get; set; }
        public virtual DbSet<TiposIdentificacion> TiposIdentificacion { get; set; }
        public virtual DbSet<TiposTratamientos> TiposTratamientos { get; set; }
        public virtual DbSet<TiposUsuarios> TiposUsuarios { get; set; }
        public virtual DbSet<Tratamientos> Tratamientos { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
