//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consultas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Consultas()
        {
            this.Tratamientos = new HashSet<Tratamientos>();
        }
    
        public int IdConsulta { get; set; }
        public string Motivo { get; set; }
        public string Diagnostico { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdHistoriaClinica { get; set; }
    
        public virtual HistoriasClinicas HistoriasClinicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tratamientos> Tratamientos { get; set; }
    }
}
