//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesFacturas
    {
        public int IdDetalleFactura { get; set; }
        public Nullable<long> Abono { get; set; }
        public Nullable<System.DateTime> FechaAbono { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdFactura { get; set; }
    
        public virtual Facturas Facturas { get; set; }
    }
}
