//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleados
    {
        public int IdEmpleado { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FechaContrato { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<long> Celular { get; set; }
        public string NumeroIdentificacion { get; set; }
        public string Email { get; set; }
        public Nullable<int> TieneUsuario { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdTipoContrato { get; set; }
        public Nullable<int> IdSexo { get; set; }
        public Nullable<int> IdTipoIdentificacion { get; set; }
        public Nullable<int> IdCargo { get; set; }
        public Nullable<int> IdTipoUsuario { get; set; }
    
        public virtual Cargos Cargos { get; set; }
        public virtual Sexos Sexos { get; set; }
        public virtual TiposContratos TiposContratos { get; set; }
        public virtual TiposIdentificacion TiposIdentificacion { get; set; }
        public virtual TiposUsuarios TiposUsuarios { get; set; }
    }
}
