//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamenesClinicos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamenesClinicos()
        {
            this.Examenes = new HashSet<Examenes>();
        }
    
        public int IdExamenClinico { get; set; }
        public string Labios { get; set; }
        public string Encias { get; set; }
        public string Carrillos { get; set; }
        public string Lengua { get; set; }
        public string Paladar { get; set; }
        public string PisoBoca { get; set; }
        public string Uvula { get; set; }
        public string GlandulasSalivales { get; set; }
        public string Observacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Examenes> Examenes { get; set; }
    }
}
