//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examenes
    {
        public int IdPacienteExamen { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdExamenClinico { get; set; }
        public Nullable<int> IdHistoriaClinica { get; set; }
    
        public virtual ExamenesClinicos ExamenesClinicos { get; set; }
        public virtual HistoriasClinicas HistoriasClinicas { get; set; }
    }
}
