//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facturas()
        {
            this.DetallesFacturas = new HashSet<DetallesFacturas>();
        }
    
        public int IdFactura { get; set; }
        public Nullable<long> Total { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<long> Saldo { get; set; }
        public string Observacion { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdPaciente { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesFacturas> DetallesFacturas { get; set; }
        public virtual Pacientes Pacientes { get; set; }
    }
}
