//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Municipios
    {
        public int IdMunicipio { get; set; }
        public string Municipio { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
    
        public virtual Departamentos Departamentos { get; set; }
    }
}
