//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacientes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pacientes()
        {
            this.Antecedentes = new HashSet<Antecedentes>();
            this.Facturas = new HashSet<Facturas>();
            this.HistoriasClinicas = new HashSet<HistoriasClinicas>();
            this.PacientesResponsables = new HashSet<PacientesResponsables>();
        }
    
        public int IdPaciente { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
        public Nullable<System.DateTime> FechaNacimiento { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public string Barrio { get; set; }
        public Nullable<long> Telefono { get; set; }
        public Nullable<long> Celular { get; set; }
        public string Ocupacion { get; set; }
        public string Aseguradora { get; set; }
        public string Vinculacion { get; set; }
        public string MotivoConsulta { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdSexo { get; set; }
        public Nullable<int> IdDepartamento { get; set; }
        public Nullable<int> IdTipoIdentificacion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Antecedentes> Antecedentes { get; set; }
        public virtual Departamentos Departamentos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Facturas> Facturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriasClinicas> HistoriasClinicas { get; set; }
        public virtual Sexos Sexos { get; set; }
        public virtual TiposIdentificacion TiposIdentificacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PacientesResponsables> PacientesResponsables { get; set; }
    }
}
