//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PacientesResponsables
    {
        public int IdPacienteResponsable { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdPaciente { get; set; }
        public Nullable<int> IdResponsable { get; set; }
    
        public virtual Pacientes Pacientes { get; set; }
        public virtual Responsables Responsables { get; set; }
    }
}
