//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Radiografias
    {
        public int IdRadiografia { get; set; }
        public string Nombre { get; set; }
        public byte[] Radiografia { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdHistoriaClinica { get; set; }
    
        public virtual HistoriasClinicas HistoriasClinicas { get; set; }
    }
}
