//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppConsultorio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tratamientos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tratamientos()
        {
            this.HistoriasClinicas = new HashSet<HistoriasClinicas>();
        }
    
        public int IdTratamiento { get; set; }
        public Nullable<int> Habilitado { get; set; }
        public Nullable<int> IdConsulta { get; set; }
        public Nullable<int> IdTipoTratamiento { get; set; }
    
        public virtual Consultas Consultas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriasClinicas> HistoriasClinicas { get; set; }
        public virtual TiposTratamientos TiposTratamientos { get; set; }
    }
}
